services:
  exemple-back-voltorbataille:
    image: exemple-back-voltorbataille
    ports:
      - 8080:8080
    environment:
      - API_GRILLE_HOST=api-grille-voltorbataille
      - API_GRILLE_PORT=8081
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=users_db
      - DB_PASSWORD=voltorbataille
      - DB_USER=voltorbataille
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
      api-grille-voltorbataille:
        condition: service_started
        restart: true

  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=users_db
      - MYSQL_PASSWORD=voltorbataille
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=voltorbataille
    ports:
      - 3310:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 10s
      retries: 5

  api-grille-voltorbataille:
    image: api-grille-voltorbataille
    ports:
      - 8081:8081